/*
 * Copyright (C) 2018 taylor.fish <contact@taylor.fish>
 *
 * This file is part of Fish MidiSlide.
 *
 * Fish MidiSlide is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Fish MidiSlide is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Fish MidiSlide.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was automatically generated by generate_plugin_data.py.

#ifndef PORTS_H
#define PORTS_H

enum {
    PORT_INPUT = 0,
    PORT_OUTPUT = 1,
    PORT_BEAT_DIVISOR = 2,
    PORT_BEND_SEMITONE_DISTANCE = 3,
    PORT_FORCED_VELOCITY = 4,
};

#endif
